### ISSUE TITLE
Documentation or Example Code

### ISSUE THREAD

**Issue by dhilowitz** [justinmakaila/iOS-FrameEncoder#1]
Hi Justin,

Thanks so much for your code! I was wondering if there was an documentation / example code on how libRTMPClient works. I've read the great blog posts by Geraint Davies about how the hardware h.264 encoding works, but I'm still trying to get a handle on how your libRTMPClient class can be used in conjunction with that. Any help you can give me would be greatly appreciated. 

All best,
Dave

**Comment by justinmakaila** [comment]
@dhilowitz, This repository has been unmaintained and out of commission for a while. I'm currently working on an all encompassing solution for streaming video. In the mean-time, you can check out https://github.com/Kickflip/kickflip-ios-sdk, which uses very similar classes to the ones in this repository.
